[package]
name = "codegraph-parser"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
codegraph-core.workspace = true
tree-sitter.workspace = true
tree-sitter-rust.workspace = true
tree-sitter-c.workspace = true
tree-sitter-cpp.workspace = true
tree-sitter-python.workspace = true
tree-sitter-javascript.workspace = true
tree-sitter-typescript.workspace = true
tree-sitter-html.workspace = true
tree-sitter-css.workspace = true
blake3.workspace = true
ignore.workspace = true
tracing.workspace = true
